import { motion } from "framer-motion"
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card"
import { Scan, HighlighterIcon, MessageSquare, Zap } from "lucide-react"

const features = [
  {
    icon: Scan,
    title: "AI Content Detection",
    description: "Advanced algorithms analyze text patterns to identify AI-generated content with high accuracy confidence scores.",
    color: "text-blue-500"
  },
  {
    icon: HighlighterIcon,
    title: "Smart Highlighting",
    description: "Instantly highlights suspicious sentences and phrases that are likely generated by AI systems.",
    color: "text-yellow-500"
  },
  {
    icon: MessageSquare,
    title: "Tone Transformation",
    description: "Rephrase content in various tones - professional, casual, polite, or witty to match your style.",
    color: "text-green-500"
  },
  {
    icon: Zap,
    title: "Browser Integration",
    description: "Seamlessly integrated into your browser workflow. No copy-pasting between different tools.",
    color: "text-purple-500"
  }
]

export function FeaturesSection() {
  return (
    <section className="py-20 px-6 bg-gradient-secondary/50">
      <div className="max-w-6xl mx-auto">
        <motion.div 
          className="text-center mb-16"
          initial={{ opacity: 0, y: 30 }}
          whileInView={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.8 }}
          viewport={{ once: true }}
        >
          <h2 className="text-4xl md:text-5xl font-bold mb-6">
            Powerful Features
          </h2>
          <p className="text-xl text-muted-foreground max-w-2xl mx-auto">
            Everything you need to detect, analyze, and transform AI-generated content into authentic human writing.
          </p>
        </motion.div>

        <div className="grid md:grid-cols-2 lg:grid-cols-4 gap-6">
          {features.map((feature, index) => (
            <motion.div
              key={feature.title}
              initial={{ opacity: 0, y: 30 }}
              whileInView={{ opacity: 1, y: 0 }}
              transition={{ duration: 0.6, delay: index * 0.1 }}
              viewport={{ once: true }}
              whileHover={{ y: -10 }}
              className="group"
            >
              <Card className="h-full bg-card/50 backdrop-blur-md border border-white/10 shadow-glass hover:shadow-elevated transition-all duration-300">
                <CardHeader className="text-center pb-4">
                  <motion.div 
                    className={`w-16 h-16 mx-auto mb-4 rounded-2xl bg-gradient-to-br from-background to-muted/50 flex items-center justify-center group-hover:scale-110 transition-transform duration-300`}
                    whileHover={{ rotate: [0, -10, 10, 0] }}
                    transition={{ duration: 0.5 }}
                  >
                    <feature.icon className={`w-8 h-8 ${feature.color}`} />
                  </motion.div>
                  <CardTitle className="text-xl">{feature.title}</CardTitle>
                </CardHeader>
                <CardContent>
                  <p className="text-muted-foreground text-center leading-relaxed">
                    {feature.description}
                  </p>
                </CardContent>
              </Card>
            </motion.div>
          ))}
        </div>
      </div>
    </section>
  )
}